name: Live Update
  
env:
  TZ: Asia/Shanghai
  
on:
  watch:
    types: [started]
  schedule:
    - cron: 15 14 * * *
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual trigger'
        required: true
        default: 'Manual Test'

permissions:
  contents: write

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
	  with:
          token: ${{ secrets.iptv }}
		  
    - name: GetTime
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S CST')"
      
    - name: Update
    run: |
      wget -q https://raw.githubusercontent.com/fanmingming/live/master/tv/m3u/ipv6.m3u -O fmm.txt
      wget -q https://iptvindex.com/tv.txt     -O index.txt
      wget -q https://live.zbds.top/tv/iptv4.txt -O zbds.txt
      wget -q https://freetv.fun/test_channels_all_original_new.txt -O freetv.txt

      {
        echo "#update on $(date +'%F %T')"
        echo "#clone from fanmingming"
        sed '/^$/d;/EXTM3U/d' fmm.txt
        echo
        echo "#clone from iptvindex"
        grep m3u index.txt || true
        echo
        echo "#clone from zbds"
        grep m3u zbds.txt || true
      } > iptv.txt

      sed -i 's/tvg-logo="" //g' iptv.txt
      rm -f fmm.txt index.txt zbds.txt

  - name: Push
    run: |
      git config user.name "github-actions[bot]"
      git config user.email "github-actions[bot]@users.noreply.github.com"
      git add iptv.txt freetv.txt
      git diff --staged --quiet || git commit -m "${{ steps.date.outputs.date }}"
      git push
	  
		
		