name: Live Update
  
env:
  TZ: Asia/Shanghai
  
on:
  watch:
    types: [started]
  schedule:
    - cron: 15 14 * * *
  workflow_dispatch:
    inputs:
      #logLevel:
        #description: 'Log level'
        #required: true
        #default: 'warning'
      tags:
        description: 'Manual trigger'
        required: true
        default: 'Manual Test'

permissions:
  contents: write

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: GetTime
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S CST')"
      
    - name: Update
      run: |
        wget https://raw.githubusercontent.com/fanmingming/live/master/tv/m3u/ipv6.m3u --no-check-certificate -O fmm.txt
		wget https://iptvindex.com/tv.txt --no-check-certificate -O index.txt
        wget https://live.zbds.top/tv/iptv4.txt --no-check-certificate -O zbds.txt
        echo "#update on"" $(date +'%Y-%m-%d %H:%M:%S')" > iptv.txt
        echo "#clone from fanmingming" >> iptv.txt
        cat fmm.txt|sed '/^$/d'|sed '/EXTM3U/d' >> iptv.txt
		echo -e >> iptv.txt
		echo "#clone from iptvindex" >> iptv.txt
        grep m3u index.txt >> iptv.txt
        echo -e >> iptv.txt
        echo "#clone from zbds" >> iptv.txt
        grep m3u zbds.txt >> iptv.txt
        sed -i 's/tvg-logo="" //g' iptv.txt
		rm fmm.txt index.txt zbds.txt
        wget https://freetv.fun/test_channels_all_original_new.txt --no-check-certificate -O freetv.txt
        mv iptv.txt freetv.txt list
		
    - name: Push
      run: |
        git config --local user.name "huangsuming"
        git config --local user.email "huangsuming@users.noreply.github.com"
        git add list/iptv.txt list/freetv.txt
        git commit -m "${{ steps.date.outputs.date }}"
        git push origin main