name: Live Update
  
env:
  TZ: Asia/Shanghai
  
on:
  watch:
    types: [started]
  schedule:
    - cron: 15 14 * * *
  workflow_dispatch:
    inputs:
      #logLevel:
        #description: 'Log level'
        #required: true
        #default: 'warning'
      tags:
        description: 'Manual trigger'
        required: true
        default: 'Manual Test'

permissions:
  contents: write

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: GetTime
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S CST')"
      
    - name: Update
      run: |
        wget https://raw.githubusercontent.com/fanmingming/live/master/tv/m3u/ipv6.m3u -O fmm.m3u
        wget https://live.zbds.top/tv/iptv4.txt --no-check-certificate -O zbds.txt
        echo "#update on"" $(date +'%Y-%m-%d %H:%M:%S')" > iptv.txt
        echo "#clone from fanmingming" >> iptv.txt
        cat fmm.m3u|sed '/^\s*$/d' >> iptv.txt
        echo -e >> iptv.txt
        echo -e >> iptv.txt
        echo "#clone from zbds" >> iptv.txt
        cat zbds.txt|sed '/^\s*$/d' >> iptv.txt
        sed -i 's/tvg-logo.*png"//g' iptv.txt
        sed -i 's/tvg-logo="" //g' iptv.txt
        mv fmm.m3u zbds.txt iptv.txt list
        
    - name: Push
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add list/fmm.m3u list/zbds.txt list/iptv.txt
        git commit -m "${{ steps.date.outputs.date }}"
        git push origin main
		